

-- Table Structure for Exchange Data

CREATE TABLE exchange_ownership (
    user_id         NUMBER,      -- Unique identifier for the user
    stock_id        VARCHAR2(50), -- Stock identifier 
    stock_count     NUMBER,      -- Number of shares owned by the user
    exchange_date   DATE,        -- Date when this record is received
    PRIMARY KEY (user_id, stock_id, exchange_date)
);



-- Table Structure for Depository Data
CREATE TABLE depository_ownership (
    user_id         NUMBER,      -- Unique identifier for the user
    stock_id        VARCHAR2(50), -- Stock identifier
    stock_count     NUMBER,      -- Number of shares owned by the user
    depository_date DATE,        -- Date when this record is received
    PRIMARY KEY (user_id, stock_id, depository_date)
);



-- Table Structure for Comparison Logs
CREATE TABLE ownership_comparison_log (
    log_id           NUMBER GENERATED BY DEFAULT AS IDENTITY, -- Auto-incremented log ID
    user_id          NUMBER,      -- User ID for the comparison
    stock_id         VARCHAR2(50), -- Stock identifier
    exchange_count   NUMBER,      -- Stock count from exchange data
    depository_count NUMBER,      -- Stock count from depository data
    comparison_date  DATE DEFAULT SYSDATE, -- Date of comparison
    result           VARCHAR2(20), -- 'MATCH' or 'MISMATCH'
    PRIMARY KEY (log_id)
);

